#!/bin/bash
file=$1
num=$2
c=0
for((i=1;i<=$num;i++))
do
        if(($num == 0))
        then
               c=$(($c+1))
        fi
done
if(($c==2))
then
	echo $num is prime >> $file.txt
	for ((i=1;i<=$num;i++))
	do
        	if((i==1||i%2==0||i%3==0||i%5==0||i%7==0))
        	then
                	if((i!=2&&i!=3&&i!=5&&i!=7))
                	then
                        	continue
                	fi
                	if((i==2||i==3||i==5||i==7))
                	then
                	        echo $i >> $file.txt
                	fi
        	else
                	echo $i >> $file.txt
        	fi
	done
else
	echo $num is not prime
fi
