#!/bin/bash
num1=$1
num2=$2
num3=$3
num4=$4
num5=$5
num6=$6
num7=$7
num8=$8
num9=$9
num10=$10
even=0
odd=0

for ((i=0;i<10;i++))
do
    if($num$i%2==0)
        then
       # echo $num$i is even number
	$even=$((even + 1))
    fi
    else
       # echo $num$i is odd number
	$odd=$((odd + 1))
    fi
