#!/bin/bash
prime=0
nprime=0
for((i=0;i<3;i++))
do
	c=0
	echo -n "enter num: "
	read a
	for((j=1;j<=a;j++))
	do
		if((a%j==0))
		then
			c=$((c+1))
		fi
	done

if((c==2))
then
	prime=$((prime+1))
else
	nprime=$((nprime+1))
fi
done
echo "prime="$prime
echo "not prime="$nprime
