#!/bin/bash
num=$1
num2=$2
num3=$3
a=0
b=0
c=0
for((i=1;i<=$num;i++))
do
        if(($num == 0))
        then
               a=$(($a+1))
        fi
done
for((i=1;i<=$num2;i++))
do
        if(($num2 == 0))
        then
               b=$(($b+1))
        fi
done
for((i=1;i<=$num3;i++))
do
        if(($num3 == 0))
        then
               c=$(($c+1))
        fi
done
if(($a==2))
then
        echo $num is prime
        for ((i=1;i<=$num;i++))
        do
                if((i==1||i%2==0||i%3==0||i%5==0||i%7==0))
                then
                        if((i!=2&&i!=3&&i!=5&&i!=7))
                        then
                                continue
                        fi
                        if((i==2||i==3||i==5||i==7))
                        then
                                echo $i
                        fi
                else
                        echo $i
                fi
        done
else
        echo $num is not prime
fi

if(($b==2))
then
        echo $num2 is prime
        for ((i=1;i<=$num2;i++))
        do
                if((i==1||i%2==0||i%3==0||i%5==0||i%7==0))
                then
                        if((i!=2&&i!=3&&i!=5&&i!=7))
                        then
                                continue
                        fi
                        if((i==2||i==3||i==5||i==7))
                        then
                                echo $i
                        fi
                else
                        echo $i
                fi
        done
else
        echo $num2 is not prime
fi

if(($c==2))
then
        echo $num3 is prime
        for ((i=1;i<=$num3;i++))
        do
                if((i==1||i%2==0||i%3==0||i%5==0||i%7==0))
                then
                        if((i!=2&&i!=3&&i!=5&&i!=7))
                        then
                                continue
                        fi
                        if((i==2||i==3||i==5||i==7))
                        then
                                echo $i
                        fi
                else
                        echo $i
                fi
        done
else
        echo $num3 is not prime
fi
