#! /bin/bash
num=$1
c=0
for((i=0;i<=3;i++))
then
        read -p "Input num : " num
        if(($num==0))
        then
               c=$(($c+1))
        fi


if(($c==2))
do
        echo $num is prime
        for ((i=1;i<=$num;i++))
        do
                if((i==1||i%2==0||i%3==0||i%5==0||i%7==0))
                then
                        if((i!=2&&i!=3&&i!=5&&i!=7))
                        then
                                continue
                        fi
                        if((i==2||i==3||i==5||i==7))
                        then
                                echo $i
                        fi
                else
                        echo $i
                fi
        done
else
        echo $num is not prime
fi
done
